=== abalustre/airbyte/airbyte-integrations/connectors/source-graphql/source_graphql/schemas/graphql_request.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["url", "http_method"],
  "properties": {
    "url": {
      "description": "url for the request, including query params. must start with http:// or https://",
      "type": "string",
      "pattern": "^http(s)?:\\/\\/.*$"
    },
    "http_method": {
      "description": "http method to use for the request",
      "type": "string",
      "enum": ["GET", "POST"]
    },
    "headers": {
      "description": "json object where keys are header names and values the values.",
      "type": "string",
      "examples": [
        "{ \"Accept-Charset\": \"utf-8\", \"Content-Type\": \"application/json\"}"
      ]
    },
    "body": {
      "description": "json body to be included in the request",
      "type": "string"
    },
    "params": {
      "description": "json params to be replaced in the url",
      "type": "string"
    }
  }
}

=== abalustre/airbyte/airbyte-integrations/connectors/source-http-request/sample_files/period_config.json
{"url": "https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/CotacaoMoedaPeriodo(moeda=@moeda,dataInicial=@dataInicial,dataFinalCotacao=@dataFinalCotacao)?@moeda=%27AUD%27&@dataInicial=%27{from}%27&@dataFinalCotacao=%27{to}%27&$format=json", "http_method": "GET", "params": "[{\"type\": \"period\", \"unit\": \"day\", \"format\": \"%m-%d-%Y\", \"start_date\": {\"variable\": \"from\", \"value\": \"current - 1\"}, \"end_date\": {\"variable\": \"to\", \"value\": \"current + 1\"}}]", "headers": "{\"Content-Type\": \"text/json\"}"}
